services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: reallysecurepasswordwhichnobodywillbeabletofindfromlookingatthegitcommits
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "1111:1111"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: reallysecurepasswordwhichnobodywillbeabletofindfromlookingatthegitcommits
      SERVER_PORT: 1111

volumes:
  mysql_data:
